# Generated by Django 4.2.7 on 2023-11-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=128, verbose_name='密码')),
                ('real_name', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('phone_num', models.CharField(max_length=16, verbose_name='电话号码')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=128, verbose_name='密码')),
                ('real_name', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('phone_num', models.CharField(max_length=16, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=32, verbose_name='订单号')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='接受时间')),
                ('send_addr', models.CharField(max_length=128, verbose_name='发件地点')),
                ('receive_addr', models.CharField(max_length=128, verbose_name='收件地点')),
                ('status', models.SmallIntegerField(choices=[(1, '派送中'), (2, '已送达'), (3, '已取货')], default=1, verbose_name='状态')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app01.normaluser', verbose_name='接受者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app01.normaluser', verbose_name='发送者')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('information', models.CharField(max_length=512, verbose_name='目前状况')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.order', verbose_name='订单')),
            ],
        ),
    ]
