# Generated by Django 4.2.7 on 2023-11-29 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_orderstatus_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='phone_num',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='手机号格式错误', regex='^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\\d{8}$')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='phone_num',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='手机号格式错误', regex='^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\\d{8}$')], verbose_name='手机号'),
        ),
    ]
